export const tokens = {
  color: {
    primary: '#1e2347',
    onPrimary: '#ffffff',
    primaryContainer: '#080d31',
    onPrimaryContainer: '#868ab5',
    secondary: '#8fae85',
    onSecondary: '#ffffff',
    secondaryContainer: '#cbecbf',
    onSecondaryContainer: '#4f6c48',
    tertiary: '#c77b4d',
    onTertiary: '#ffffff',
    tertiaryContainer: '#431a00',
    onTertiaryContainer: '#c67a4d',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    surface: '#fcf9f2',
    onSurface: '#1c1c18',
    surfaceVariant: '#e5e2db',
    onSurfaceVariant: '#46464e',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f6f3ec',
    surfaceContainer: '#f1eee7',
    surfaceContainerHigh: '#ebe8e1',
    surfaceContainerHighest: '#e5e2db',
    inverseSurface: '#31312c',
    inverseOnSurface: '#f3f0e9',
    inversePrimary: '#bfc3f1',
    outline: '#77767f',
    outlineVariant: '#c7c5cf',
    background: '#fcf9f2',
    onBackground: '#1c1c18',
    matchSuccess: '#8fae85',
    matchWarning: '#d4a843',
    matchDanger: '#c77b4d',
  },
  font: {
    family: "'Noto Sans', 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    displayLg: { size: '48px', weight: 700, lineHeight: 1.2, letterSpacing: '-0.02em' },
    headlineLg: { size: '32px', weight: 700, lineHeight: 1.3 },
    headlineMd: { size: '24px', weight: 600, lineHeight: 1.4 },
    bodyLg: { size: '18px', weight: 400, lineHeight: 1.6 },
    bodyMd: { size: '16px', weight: 400, lineHeight: 1.6 },
    labelMd: { size: '14px', weight: 500, lineHeight: 1.4, letterSpacing: '0.01em' },
  },
  spacing: {
    xs: '4px',
    sm: '12px',
    md: '24px',
    lg: '40px',
    xl: '64px',
    gutter: '24px',
    containerMax: '1280px',
  },
  radius: {
    sm: '4px',
    md: '8px',
    lg: '12px',
    xl: '16px',
    xxl: '24px',
    full: '9999px',
  },
  shadow: {
    resting: '0 4px 20px rgba(30, 35, 71, 0.05)',
    hover: '0 12px 32px rgba(30, 35, 71, 0.08)',
  },
} as const;
